CREATE TABLE FORUM_POLLS_OPTIONS(
ID INT,
CONSTRAINT FORUM_ID PRIMARY KEY (ID),
ID_POST INT,
CONSTRAINT ID_POST_FK FOREIGN KEY(ID_POST)
REFERENCES FORUM_POSTS (ID),
TITLE VARCHAR(64),
DATE_ TIMESTAMP
);

CREATE TABLE FORUM_POSTS(
ID INT,
CONSTRAINT POST_ID PRIMARY KEY (ID),
ID_SUBCATEGORY INT,
CONSTRAINT ID_SUBCATEGORY_FK FOREIGN KEY(ID_SUBCATEGORY)
REFERENCES FORUM_SUBCATEGORIES (ID),
ID_USER INT,
CONSTRAINT ID_USER_FK FOREIGN KEY(ID_USER)
REFERENCES USERS (ID),
PARENT_POST INT,
CONSTRAINT PARENT_POST_FK FOREIGN KEY(PARENT_POST)
REFERENCES FORUM_CATEGORIES (ID),
TITLE VARCHAR(90),
CONTENT_ TEXT,
IS_POLL NUMBER(1,0),
DATE_ TIMESTAMP,
IP VARCHAR(20)
);

CREATE TABLE FORUM_POLLS_OPTIONS_VOTES(
ID INT,
CONSTRAINT POLLS_OPTION_ID PRIMARY KEY (ID),
ID_POLL_OPTION INT,
CONSTRAINT ID_POLLS_OPTIONS_FK FOREIGN KEY(ID_POLL_OPTION)
REFERENCES FORUM_POLLS_OPTIONS (ID),
ID_USER INT,
CONSTRAINT ID_USER_FK FOREIGN KEY(ID_USER)
REFERENCES USERS (ID),
DATE_ TIMESTAMP,
IP VARCHAR(20)
);

CREATE TABLE USERS (
ID INT,
CONSTRAINT USERS_ID PRIMARY KEY (ID),
NIK VARCHAR(16),
PASSWORD VARCHAR(128),
EMAIL VARCHAR(128),
DATE_ TIMESTAMP,
KARMA FLOAT(9,2),
IP VARCHAR(20)
);

CREATE TABLE FORUM_CATEGORIES (
ID INT,
TITLE VARCHAR(64),
DESCRIPTION TEXT,
DATE_ TIMESTAMP,
IP VARCHAR(20)
);

CREATE TABLE FORUM_SUBCATEGORIES(
ID INT,
CONSTRAINT SUBCATEGORIES_ID PRIMARY KEY (ID),
ID_CATEGORY INT,
CONSTRAINT SUBCATEGORY_FK FOREIGN KEY(ID_CATEGORY)
REFERENCES FORUM_SUBCATEGORIES (ID),
TITLE VARCHAR(45),
DESCRIPTION TEXT,
DATE_ TIMESTAMP,
IP VARCHAR(20)
);