CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER,
CONSTRAINT PRODUCT_ID PRIMARY KEY(PRODUCT_ID),
PRODUCT_NAME VARCHAR2(50),
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_FK FOREIGN KEY(SUPPLIER_ID)
REFERENCES SUPPLIERS(SUPPLIER_ID),
QUANTITY_PER_UNIT NUMBER,
UNIT_PRICE DECIMAL(18,2),
UNITS_IN_STOCK INT,
UNITS_ON_ORDER INT,
REORDER_LEVEL INT,
DISCONTINUED NUMBER(1,0)
);

CREATE TABLE SUPPLIERS(
SUPPLIER_ID NUMBER,
CONSTRAINT SUPPLIER_ID PRIMARY KEY(SUPPLIER_ID),
COMPANY_NAME VARCHAR2(50),
CONTACT_NAME VARCHAR2(50),
ADDRESS VARCHAR2(50),
CITY VARCHAR2(50),
REGION VARCHAR2(50),
POSTAL_CODE NUMBER,
COUNTRY VARCHAR2(50),
PHONE NUMBER,
FAX NUMBER,
HOME_PAGE
);

CREATE TABLE ORDERS(
ORDER_ID NUMBER,
CONSTRAINT ORDER_ID PRIMARY KEY(ORDER_ID),
CUSTOMER_ID NUMBER,
CONSTRAINT CUSTOMER_ID FOREIGN KEY(CUSTOMER_ID)
REFERENCE CUSTOMERS (CUSTOMER_ID),
EMPLOYEE_ID NUMBER,
CONSTRAINT EMPLOYEE_ID FOREIGN KEY(EMPLOYEE_ID)
REFERENCE CUSTOMERS (EMPLOYEE_ID),
ORDER_DATE TIMESTAMP,
REQUIRED_DATE TIMESTAMP,
SHIPPED_DATE TIMESTAMP,
SHIP_VIA NUMBER,
CONSTRAINT SHIP_VIA  FOREIGN KEY(EMPLOYEE_ID)
REFERENCE CUSTOMERS (EMPLOYEE_ID),
UNIT_PRICE DECIMAL(18,2),
UNITS_IN_STOCK INT,
UNITS_ON_ORDER INT,
REORDER_LEVEL INT,
DISCONTINUED NUMBER(1,0)
);