CREATE TABLE MOVIE (
ID NUMBER,
CONSTRAINT MOVIE_ID PRIMARY KEY(ID),
TITLE VARCHAR2(50) NOT  NULL UNIQUE,
DIRECTOR VARCHAR2(50) NOT  NULL UNIQUE,
YEAR_ NUMBER   CHECK ( YEAR_>1900 AND YEAR_<=2019 ),
LENGTH_MINS NUMBER CHECK(LENGTH_MINS>10 AND LENGTH_MINS<200)
);