SELECT *  FROM MOVIE GROUP BY DIRECTOR;

SELECT SUM(DOMESTIC_SALES + INTERNATIONAL) FROM MOVIE_STAT
WHERE EXISTS(SELECT * FROM MOVIE WHERE ID=MOVIE_STAT.MOVIE_ID GROUP BY DIRECTOR );

SELECT * FROM MOVIE ORDER BY YEAR_NUMBER DESC;

SELECT * FROM MOVIE_STAT ORDER BY INTERNATIONAL_SALES DESC;
