SELECT  COUNT(*)  FROM MOVIE GROUP BY DIRECTOR ;

SELECT movie.director,SUM(MOVIE_STAT.DOMESTIC_SALES), SUM(MOVIE_STAT.INTERNATIONAL_SALES)  FROM MOVIE_STAT,movie
WHERE MOVIE.ID=MOVIE_STAT.MOVIE_ID
GROUP BY MOVIE.DIRECTOR;

SELECT * FROM MOVIE ORDER BY YEAR_ DESC;

SELECT * FROM MOVIE_STAT ORDER BY INTERNATIONAL_SALES DESC;
